load_chat_key = "kp_1"
send_chat_key = "kp_2"
console_log_path = "C:/Program Files (x86)/Steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/console.log"
exec_path = "C:/Program Files (x86)/Steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/cfg/chat.cfg"
command_prefix = "!,@"

[database]
host = "localhost"
port = 5432
database = "fishing_bot"
user = "bot_user"
password = "bot_password"
pause_buttons = "b,tab,y,`,alt+tab"
resume_buttons = "enter,esc"

[adapters.cs2]
language = "sv_SE"

[adapters.discord]
language = "en_US"
